name: Build and Test

on:
  push:
    branches: [ devTest ]
  pull_request:
    branches: [ devTest ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверка репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Установка CMake
      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1

      # Шаг 3: Установка библиотек и зависимостей
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libdrogon-dev libgtest-dev cmake build-essential

      # Шаг 4: Сборка GTest
      - name: Build GTest
        run: |
          cd /usr/src/gtest
          sudo cmake .
          sudo make
          sudo cp *.a /usr/lib

      # Шаг 5: Сборка проекта с CMake
      - name: Configure and Build
        run: |
          cmake -S . -B build
          cmake --build build

      # Шаг 6: Запуск тестов
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
